
[TagConfig]
	#A list of mod ids sorted by preference when getting an Item for a tag
	ITEM_PREFERENCE = [
		"minecraft",
		"alltheores",
		"kubejs",
		"thermal",
		"mekanism",
		"create",
		"immersiveengineering",
		"occultism",
		"ae2",
		"ftbic",
		"chemlib",
		"biggerreactors"
	]
