
#General configuration options.
[General]
	#Mod ids (in order) to prioritize using items for when generating the cucumber-tags.json file.
	modTagPriorities = [
		"minecraft",
		"alltheores",
		"kubejs",
		"thermal",
		"mekanism",
		"create",
		"immersiveengineering",
		"occultism",
		"ae2",
		"ftbic",
		"chemlib",
		"biggerreactors"
	]
