#A list of class:method strings (render methods) that the dark shader will not be applied to.
#Each string consists of the class and the method (or any substring) to block the dark shader.
#For example, 'renderHunger' is sufficient to block 'net.minecraftforge.client.gui.overlay.ForgeGui:renderFood' (either will work).
METHOD_SHADER_BLACKLIST = ["mezz.jei.common.render.FluidTankRenderer:drawTextureWithMasking", "mezz.jei.library.render.FluidTankRenderer:drawTextureWithMasking", "renderCrosshair", "shadows.packmenu.logo.Logo:draw", "shadows.packmenu.ExtendedMenuScreen:m88315", "shadows.packmenu.buttons.JsonButton:renderImageButton", "m_93080_", "net.minecraft.client.gui.screens.TitleScreen", "renderSky", "m_202423_", "renderHotbar", "m_93009_", "m_193837_", "setupOverlayRenderState", "net.minecraftforge.client.gui.overlay.ForgeGui", "renderFood", "renderExperienceBar", "m_93071_"]
#Enabling this config will (every 5 seconds) dump which methods were used to render GUIs that the dark shader was applied to
#The dump will consist of a list of class:method strings, e.g. 'net.minecraftforge.client.gui.overlay.ForgeGui:renderFood'
#Use this feature to help find the render method strings of GUIs you would like to blacklist.
METHOD_SHADER_DUMP = false

["Button Position"]
	#Pixels away from the left of the GUI in the x axis
	#Range: > 0
	X = 64
	#Pixels away from the bottom of the GUI in the y axis
	#Range: > 0
	Y = 0

	["Button Position"."Main Menu Button"]
		#Enabled
		SHOW = true
		#Pixels away from the left of the GUI in the x axis
		#Range: > 0
		MAIN_X = 4
		#Pixels away from the bottom of the GUI in the y axis
		#Range: > 0
		MAIN_Y = 40

