
["Button Position"]
	#Pixels away from the bottom left of the GUI in the x axis
	#Range: > 0
	X = 64
	#Pixels away from the bottom left of the GUI in the y axis
	#Range: > 0
	Y = 0
	NAME = "Dark Mode"

["Main Menu Button"]
	#Enabled
	SHOW = false
	#Pixels away from the bottom left of the GUI in the x axis
	#Range: > 0
	X = 4
	#Pixels away from the bottom left of the GUI in the y axis
	#Range: > 0
	Y = 40
	NAME = "Dark Mode"

